-- AlterTable
ALTER TABLE "admin" ALTER COLUMN "phone" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "doctor" ALTER COLUMN "phone" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "nurse" ALTER COLUMN "phone" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "staff" ALTER COLUMN "phone" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "user" ALTER COLUMN "phone" SET DATA TYPE BIGINT;
